FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.app.json tsconfig.json tsconfig.node.json ./
COPY src ./src
COPY public ./public
COPY index.html vite.config.ts postcss.config.js tailwind.config.js ./

RUN npm install
RUN npm run build

FROM node:18-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
